apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-projects-sqlite
spec:
  type: database
  target: sample-projects-sqlite
  x-database:
    client: better-sqlite3
    connection:
      filename: ../../examples/project-metadata.db
    tableName: project_metadata
    where:
      - column: source_name
        equals: sample-projects
    updatedAtField: modified_at
    locationKey: 'sample:{{ item.entityRef }}'
    entity:
      apiVersion: kabang.cloud/v1
      kind: Project
      metadata:
        name: '{{ item.project_name }}'
        title: '{{ item.project_title }}'
        description: '{{ item.project_description }}'
        annotations:
          example.com/source-row-id: '{{ item.id }}'
      spec:
        owner: '{{ item.owner_ref }}'
        team: '{{ item.team_ref }}'
